### PR TITLE
fix(metrics): more duration histogram buckets

### LINKED ISSUE #135: Histogram buckets are too small
## Problem

HTTP gateway requests for non-cached blocks can often take much longer than a couple of seconds. In fact, it's not uncommon for them to take ~60 seconds or more.

Given that, the current bucket configuration for the histograms exposed by Rainbow don't make sense, since their tuned for much quicker responses which are rather unlikely in an uncontrolled peer-to-peer network:

https://github.com/ipfs/rainbow/blob/ad18bc8308cb352329258580e2dd98ec633b1aa4/metrics.go#L29

## Suggestion

Add a bunch of larger bucket sizes, like we do in boxo:

https://github.com/ipfs/boxo/blob/0f223aada9b8beefe449b94ee9601d917f482121/gateway/metrics.go#L17-L20

Related: https://github.com/ipshipyard/waterworks-infra/issues/141

### PR DESCRIPTION
**Pull request by lidel**
Closes #135

### CODE REVIEW

File: metrics.go [hunk 1]
```diff
@@ -19,14 +19,17 @@ func registerVersionMetric(version string) {
 	m.Set(1)
 }
 
+// Duration histograms  use fixed definition here, as we don't want to break existing buckets if we need to add more.
+var defaultDurationHistogramBuckets = []float64{0.05, 0.1, 0.2, 0.5, 1, 2, 5, 10, 30, 60, 120, 240, 480, 960, 1920}
```
Comment (lidel) [inline metrics.go:23]: :warning: Boxo uses `0.25` but we had `0.2` bucket already, so I kept `0.2` to maintain continuity with historical histogram.

@2color lmk if you feel we should change it to `0.25` to have the same buckets everywhere.

Comment (2color) [reply metrics.go:23]: I would probably use the same buckets as Boxo for easier aggregation, since Rainbow exposes all the metrics coming from boxo too.

Comment (2color) [reply metrics.go:23]: Generally speaking, metrics aren't supposed to be kept for that long (not actually sure what's our retention), so any challenges that may arise for past data (though these would be minor since you can still aggregate, just with less granularity) would be minimal.

Comment (2color) [reply metrics.go:23]: Final point: from my own observations, the lower buckets don't matter so much since requests that typically hit Rainbow take in the order of seconds. 

```suggestion
var defaultDurationHistogramBuckets = []float64{0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 30, 60, 120, 240, 480, 960, 1920}
```
