### PR TITLE
fix: expose routing_http_client* metrics

### LINKED ISSUE #261: Expose boxorouting_http_client_* metrics
Rainbow seems to be missing /routing/v1 client metrics defined in [boxo/routing/http/client/measures.go#L19-L20](https://github.com/ipfs/boxo/blob/eff95ad4d9470aab06b40f467e07293bf0936816/routing/http/client/measures.go#L19-L20):
- `routing_http_client_latency`
- `routing_http_client_length`

We need them, to be able to visualize request/success rate per `host`.

### PR DESCRIPTION
**Pull request by hsanjuan**
These metrics are using opencensus, so the part that plugs opencensus to prometheus was missing. Setup inspired by what Kubo does.

With this, the metrics will appear in the form `ipfs_routing_http_client_*`.

Verified that it works by hand.

Fixes #261

### CODE REVIEW

File: setup_routing.go [hunk 1]
```diff
@@ -22,10 +23,32 @@ import (
...
+		OnError: func(err error) {
+			goLog.Errorf("ocprom error: %w", err)
+		},
+	})
+	if err != nil {
+		goLog.Errorf("routing metrics: error creating exporter: %w", err)
+		return
+	}
+	view.RegisterExporter(pe)
+	view.SetReportingPeriod(2 * time.Second)
```
Comment (lidel) [inline setup_routing.go:49]: - [ ] check if we need 2s resolution, i think Prometheus Scrape Interval is ~15s

Comment (lidel) [reply setup_routing.go:49]: our grafana is polling every 30s, so 2s is overkill for prod, but it may be useful for local debugging.

let's keep 2s to match Kubo, we can adjust in future PR if 2s turns out to be too costly

**Review by lidel — APPROVED** [review]
